### ISSUE TITLE
Чит на заказ

### ISSUE THREAD

**Issue by ghost** [GeneralFire/WarThunderHack#1]
Здраствуйте! Возможно ли у вас заказать чит для АБ?

**Comment by GeneralFire** [comment]
> Здраствуйте! Возможно ли у вас заказать чит для АБ?

Боюсь, что то что вы видите на скриншотах - предел по функционалу для того, что я хочу писать, т.е. максимум примерные маркеры прицеливания для реалистичных воздушных боев.
Для танковых необходимо обходить EAC.

В общем, если интересует именно маркеры для воздушных РБ, то пишите в дискорд: PYLOH OBOEB#4164
