### ISSUE TITLE
dll

### ISSUE THREAD

**Issue by bottah33** [GeneralFire/WarThunderHack#2]
could u send the compiled version here/just the dll since i got issues with compiling it thanks

**Comment by bottah33** [comment]
well i got the dll but now it says when i inject failed to create devide and swapchain any fix?

хорошо, я получил dll, но теперь он говорит, что когда я вводил, не удалось создать раздел и свопчейн, какое-либо исправление?

**Comment by GeneralFire** [comment]
it's probably very outdated: not only offsets, maybe render engine too.
dx11 hook based - [Universal-D3D11-Hook](https://github.com/Rebzzel/Universal-D3D11-Hook) copy-paste. Verify thats still use directX engine (in setting, maybe game also support another renderer).
If you sure that's using DirectX11, try [Rake's hook](https://github.com/guided-hacking/GH_D3D11_Hook)

**Comment by EnjoyLeole** [comment]
> it's probably very outdated: not only offsets, maybe render engine too. dx11 hook based on [Universal-D3D11-Hook](https://github.com/Rebzzel/Universal-D3D11-Hook) copy-paste. Verify thats still use directX engine (in setting, maybe game also support another renderer). If you sure that's using DirectX11, try [Rake's hook](https://github.com/guided-hacking/GH_D3D11_Hook)

Any tips for updating offsets?  Thanks a lot.  The playerListOffset store pointers of player, it's hard to find playerListOffset table from single player's location address

**Comment by EnjoyLeole** [comment]
address of player name seems easy to findout, could take any advantage on this? is there any pattern could be use?

**Comment by GeneralFire** [comment]
> > it's probably very outdated: not only offsets, maybe render engine too. dx11 hook based on [Universal-D3D11-Hook](https://github.com/Rebzzel/Universal-D3D11-Hook) copy-paste. Verify thats still use directX engine (in setting, maybe game also support another renderer). If you sure that's using DirectX11, try [Rake's hook](https://github.com/guided-hacking/GH_D3D11_Hook)
> 
> Any tips for updating offsets? Thanks a lot. The playerListOffset store pointers of player, it's hard to find playerListOffset table from single player's location address

1. Explore functions that use offsets, save call graph. It facilitate the search process after updates.
2. Get actual from unknowncheats forum in War Thunder thread.

Its hardly to take any advantage on player's names. Core info to plot predition markers is the location and velocity vector.

**Comment by bottah33** [comment]
u planning it on updating it any time soon cause i rlly dont know none bout coding only thing i can do is compile lmao

**Comment by GeneralFire** [comment]
> u planning it on updating it any time soon cause i rlly dont know none bout coding only thing i can do is compile lmao

Really not. I don't play it anymore. 


> and ppl rlly need any type of aimbot etc for this game

Check unknowncheats forum, it contains internal game logic pseudocode and more over, complete implementations of bullet trajectory algorithms.
